"""Pure data contracts for chair-stand offline validation."""

from .schema import (
    SCHEMA_VERSION,
    CaseResult,
    ComparisonResult,
    DetectedOutcome,
    ExpectedOutcome,
    ExpectedValidity,
    FailureCategory,
    GenerationProvenance,
    ManifestValidationError,
    ProcessingStatus,
    Sex,
    SourceType,
    SubjectAnnotation,
    TimingAnnotation,
    ValidationCase,
    ValidationManifest,
    ViewMetadata,
    compare_outcomes,
    load_manifest,
    manifest_from_payload,
    sha256_file,
    sha256_json,
)

__all__ = [
    "SCHEMA_VERSION",
    "CaseResult",
    "ComparisonResult",
    "DetectedOutcome",
    "ExpectedOutcome",
    "ExpectedValidity",
    "FailureCategory",
    "GenerationProvenance",
    "ManifestValidationError",
    "ProcessingStatus",
    "Sex",
    "SourceType",
    "SubjectAnnotation",
    "TimingAnnotation",
    "ValidationCase",
    "ValidationManifest",
    "ViewMetadata",
    "compare_outcomes",
    "load_manifest",
    "manifest_from_payload",
    "sha256_file",
    "sha256_json",
]
